# Generated by Django 3.2.23 on 2024-01-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jobname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
