# Generated by Django 3.2.23 on 2024-01-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_auto_20240101_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='jobname',
        ),
        migrations.RemoveField(
            model_name='application',
            name='username',
        ),
    ]
