# Generated by Django 3.2.23 on 2024-01-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_auto_20240101_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='std_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.student'),
        ),
    ]
